language: node_js

branches:
  only:
    - master

node_js:
  - "10"

before_install:
  - npm install --global @gridsome/cli
  - yarn

script:
  - yarn build

after_success:
  - cd dist
  - git init
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add .
  - git commit -m "$TRAVIS_COMMIT_MESSAGE"
  - git remote add origin https://${GITHUB_TOKEN}@github.com/rahmanda/rahmanda.github.io.git > /dev/null 2>&1
  - git push --force --quiet --set-upstream origin master
